
/* 
 * Copyright (c) 2003 LAAS/CNRS
 * All rights reserved.
 *
 * Redistribution and use  in source  and binary  forms,  with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *   1. Redistributions of  source  code must retain the  above copyright
 *      notice, this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright
 *      notice,  this list of  conditions and the following disclaimer in
 *      the  documentation  and/or  other   materials provided  with  the
 *      distribution.
 *
 * THIS  SOFTWARE IS PROVIDED BY  THE  COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND  ANY  EXPRESS OR IMPLIED  WARRANTIES,  INCLUDING,  BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES  OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR  PURPOSE ARE DISCLAIMED. IN  NO EVENT SHALL THE COPYRIGHT
 * HOLDERS OR      CONTRIBUTORS  BE LIABLE FOR   ANY    DIRECT, INDIRECT,
 * INCIDENTAL,  SPECIAL,  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN  CONTRACT, STRICT LIABILITY, OR
 * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
 * USE   OF THIS SOFTWARE, EVEN   IF ADVISED OF   THE POSSIBILITY OF SUCH
 * DAMAGE.
 */

/*
 * Automatically generated by GenoM : do not edit by hand
 * Read data from the posters produced by the module proximity
 */


#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>

#include <h2devLib.h>
#include <portLib.h>
#include <posterLib.h>

#include "proximityPosterLib.h"
#include "proximityPrint.h"
#include "proximityEndian.h"

#include <genom/genom.h>
#include <genom/h2endian.h>

/* Id. du poster de controle */
static POSTER_ID proximityCntrlPosterId=(POSTER_ID)NULL;
static H2_ENDIANNESS posterDataEndianness;

/*  prototypes de la bibliotheque printState */
extern char const * h2GetEvnStateString(int num);

/* ---------------- LE POSTER DE CONTROLE ------------------------------ */

/* ----------------------------------------------------------------------
 *
 *  proximityCntrlPosterRead - Lecture du poster de controle du module
 *
 */

POSTER_ID proximityCntrlPosterID () { return proximityCntrlPosterId; }

STATUS proximityCntrlPosterRead (PROXIMITY_CNTRL_STR *proximityCntrlStrId)
{  
  if (!proximityCntrlPosterId)
    proximityCntrlPosterInit();
  if (posterRead (proximityCntrlPosterId, 0, (void *) proximityCntrlStrId, 
	      sizeof(PROXIMITY_CNTRL_STR)) != sizeof(PROXIMITY_CNTRL_STR))
    return ERROR; 
  return OK;
}

STATUS proximityCntrlInstancePosterRead (const char *name, 
                                        PROXIMITY_CNTRL_STR *proximityCntrlStrId)
{
  char posterName[H2_DEV_MAX_NAME];
  POSTER_ID p;
  
  snprintf(posterName, sizeof(posterName), "%sCntrl", name);
  if (posterFind(posterName, &p) == ERROR)
    return ERROR;

  if (posterRead(p, 0, (void *) proximityCntrlStrId, 
	      sizeof(PROXIMITY_CNTRL_STR)) != sizeof(PROXIMITY_CNTRL_STR))
    return ERROR; 
  return OK;
}

/* ---------------- LES POSTERS FONCTIONNELS ------------------------------ */

static POSTER_ID StatusPosterId=(POSTER_ID)NULL;

/* -- posterInit ------------------------------------------------------- */

STATUS proximityPosterInit(void)
{
  int status = OK;

  proximityRecordH2errMsgs();

  if (proximityCntrlPosterInit() == ERROR) {
    status = ERROR;
  }
  if (proximityStatusPosterInit() == ERROR) {
    status = ERROR;
  }
  return(status);
}

/* --  Cntrl ------------------------------------------------- */

STATUS proximityCntrlPosterInit(void)
{
  if (posterFind(PROXIMITY_CNTRL_POSTER_NAME, &proximityCntrlPosterId) == ERROR) {
     h2perror("proximityCntrlPosterInit");
     return ERROR;
  }
  if (posterEndianness(proximityCntrlPosterId, &posterDataEndianness) == ERROR) {
    h2perror("proximityCntrlPosterInit");
    return ERROR;
  }
  return OK;
}

/* --  Status ------------------------------------------------- */

STATUS proximityStatusPosterInit(void)
{
  if (posterFind(PROXIMITY_STATUS_POSTER_NAME, &StatusPosterId) == ERROR) {
     h2perror("proximityStatusPosterInit");
     return ERROR;
  }
  if (posterEndianness(StatusPosterId, &posterDataEndianness) == ERROR) {
    h2perror("proximityStatusPosterInit");
    return ERROR;
  }
  return OK;
}

/* --  Status ------------------------------------------------- */

POSTER_ID proximityStatusPosterID() { return StatusPosterId; }
STATUS proximityStatusPosterRead(PROXIMITY_STATUS_POSTER_STR *x)
{
  if (StatusPosterId == (POSTER_ID)NULL) {
     if (proximityStatusPosterInit() == ERROR) {
        h2perror("proximityStatusPosterInit");
        return ERROR;
     }
  }
  if (posterRead(StatusPosterId, 0, (char *)x, sizeof(*x))
           != sizeof(*x)) {
    h2perror("proximityStatusPosterRead:");
    return ERROR;
  }
  if (posterDataEndianness != H2_LOCAL_ENDIANNESS)
     endianswap_struct_PROXIMITY_STATUS_POSTER_STR(x, 0, NULL);
  return OK;
}

STATUS proximityStatusInstancePosterRead(const char *name, PROXIMITY_STATUS_POSTER_STR *x)
{
  char posterName[H2_DEV_MAX_NAME];
  POSTER_ID p;

  snprintf(posterName, sizeof(posterName), "%sStatus", name);
  if (posterFind(posterName, &p) == ERROR) {
     h2perror("posterFind");
     return ERROR;
  }
  if (posterRead(p, 0, (char *)x, sizeof(*x))
           != sizeof(*x)) {
     h2perror("proximityStatusNamePosterRead");
     return ERROR;
  }
  return OK;
}

/* --  Status -> sensors ---------------------------------------- */

STATUS proximityStatussensorsPosterRead(PROXIMITYSENSORS *sensors /* struct PROXIMITYSENSORS */)
{
  PROXIMITY_STATUS_POSTER_STR *x = NULL;
  int offset = offsetof(PROXIMITY_STATUS_POSTER_STR, sensors);
  int size = sizeof(x->sensors);
  int *dims = NULL;

  if (StatusPosterId == (POSTER_ID)NULL) {
     if (proximityStatusPosterInit() == ERROR) {
        h2perror("proximityStatusPosterInit");
        return ERROR;
     }
  }
  if (posterRead(StatusPosterId, offset, (char *)(sensors), size) != size) {
    h2perror("proximityStatusPosterRead read");
    return ERROR;
  }
  if (posterDataEndianness != H2_LOCAL_ENDIANNESS)
     endianswap_struct_PROXIMITYSENSORS(sensors, 0, dims);
  return OK;
}

STATUS proximityStatussensorsInstancePosterRead(const char *name, PROXIMITYSENSORS *sensors)
{
  char posterName[H2_DEV_MAX_NAME];
  POSTER_ID p;
  PROXIMITY_STATUS_POSTER_STR *x = NULL;
  int offset = offsetof(PROXIMITY_STATUS_POSTER_STR, sensors);
  int size = sizeof(x->sensors);

  snprintf(posterName, sizeof(posterName), "%sStatus", name);
  if (posterFind(posterName, &p) == ERROR) {
     h2perror("posterFind");
     return ERROR;
  }
  if (posterRead(p, offset, (char *)sensors, size)
           != size) {
     h2perror("proximityStatusNamedPosterRead");
     return ERROR;
  }
  return OK;
}


