/*
 * Automatically generated by GenoM : do not edit by hand
 *
 * Copyright (C) 2004-2007 LAAS/CNRS
 */

#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>

#include <portLib.h>
#include <posterLib.h>
#include "proximityPrint.h"

/* --  Status  ------------------------------------------------- */

STATUS proximityStatusPosterWrite(POSTER_ID pid, PROXIMITY_STATUS_POSTER_STR *x)
{
  return (posterWrite(pid, 0, (char *)x, sizeof(*x))
            == sizeof(*x) ? OK : ERROR);
}

/* --  Status -> sensors ---------------------------------------- */

STATUS proximityStatussensorsPosterWrite (POSTER_ID pid, PROXIMITYSENSORS *sensors /* struct PROXIMITYSENSORS */)
{
  PROXIMITY_STATUS_POSTER_STR *x = NULL;
  int size = sizeof(x->sensors);
  return (posterWrite(pid, offsetof(PROXIMITY_STATUS_POSTER_STR, sensors), (char *)(sensors), size) 
	== size ? OK : ERROR);
}


