/*
 * Automatically generated by GenoM : do not edit by hand
 *
 * Copyright (C) 2004-2007 LAAS/CNRS
 */

#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>

#include <portLib.h>
#include <posterLib.h>
#include "genom/genomError.h"

#include "proximityScan.h"

#include "proximityEndian.h"


