/*
 * Automatically generated by GenoM: do not edit by hand
 *
 * Copyright (C) 2003-2007 LAAS/CNRS
 */

#include <portLib.h>
#include "proximityEndian.h"

void endianswap_struct_PROXIMITY_STATUS_POSTER_STR(struct PROXIMITY_STATUS_POSTER_STR *x, int nDim, int *dims)
{
  FOR_EACH_elt(nDim,dims) {
    endianswap_struct_PROXIMITYSENSORS(&((x+elt)->sensors), 0, NULL);

  } END_FOR
}

void endianswap_struct_PROXIMITY_STR(struct PROXIMITY_STR *x, int nDim, int *dims)
{
  FOR_EACH_elt(nDim,dims) {
    endianswap_struct_PROXIMITYSENSORS(&((x+elt)->sensors), 0, NULL);

  } END_FOR
}

void endianswap_struct_PROXIMITYSENSORS(struct PROXIMITYSENSORS *x, int nDim, int *dims)
{
  FOR_EACH_elt(nDim,dims) {
    endianswap_int(&((x+elt)->num_left_sensors), 0, NULL);

    { int dims[1] = {10};
      endianswap_double((double *)((x+elt)->left_sensors), 1, dims); }

    endianswap_int(&((x+elt)->num_right_sensors), 0, NULL);

    { int dims[1] = {10};
      endianswap_double((double *)((x+elt)->right_sensors), 1, dims); }

    endianswap_int(&((x+elt)->num_top_sensors), 0, NULL);

    { int dims[1] = {10};
      endianswap_double((double *)((x+elt)->top_sensors), 1, dims); }

    endianswap_int(&((x+elt)->num_back_sensors), 0, NULL);

    { int dims[1] = {10};
      endianswap_double((double *)((x+elt)->back_sensors), 1, dims); }

  } END_FOR
}


/* ======================== ENDIAN DES TYPEDEF ============================= */

void endianswap_PROXIMITYSENSORS(PROXIMITYSENSORS *x, int nDim, int *dims)
{
  FOR_EACH_elt(nDim,dims) {
    endianswap_struct_PROXIMITYSENSORS(&(*(x+elt)), 0, NULL);

  } END_FOR
}

void endianswap_PROXIMITY_STR(PROXIMITY_STR *x, int nDim, int *dims)
{
  FOR_EACH_elt(nDim,dims) {
    endianswap_struct_PROXIMITY_STR(&(*(x+elt)), 0, NULL);

  } END_FOR
}

void endianswap_PROXIMITY_STATUS_POSTER_STR(PROXIMITY_STATUS_POSTER_STR *x, int nDim, int *dims)
{
  FOR_EACH_elt(nDim,dims) {
    endianswap_struct_PROXIMITY_STATUS_POSTER_STR(&(*(x+elt)), 0, NULL);

  } END_FOR
}


