/*
 * Automatically generated by GenoM: do not edit by hand
 *
 * Copyright (C) 2003 LAAS/CNRS
 */

#ifndef ENDIANSWAP_PROXIMITY_H
#define ENDIANSWAP_PROXIMITY_H
#include <stdio.h>
#include <stdlib.h>


#include <portLib.h>
#include <genom/printScan.h>
#include <genom/h2endian.h>
#include "proximityPosterLib.h"

/* Protoypes */

extern void endianswap_struct_PROXIMITY_STATUS_POSTER_STR ( struct PROXIMITY_STATUS_POSTER_STR *x, int nDim, int *dims);
extern void endianswap_struct_PROXIMITY_STR ( struct PROXIMITY_STR *x, int nDim, int *dims);
extern void endianswap_struct_PROXIMITYSENSORS ( struct PROXIMITYSENSORS *x, int nDim, int *dims);

/* ======================== ENDIAN DES TYPEDEF ============================= */

extern void endianswap_PROXIMITYSENSORS ( PROXIMITYSENSORS *x, int nDim, int *dims);
extern void endianswap_PROXIMITY_STR ( PROXIMITY_STR *x, int nDim, int *dims);
extern void endianswap_PROXIMITY_STATUS_POSTER_STR ( PROXIMITY_STATUS_POSTER_STR *x, int nDim, int *dims);
#endif

