/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "controller.h"

int *
initcontroller_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
movecontroller_1_svc(POSITION *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
movetocontroller_1_svc(POSITION *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
rotatecontroller_1_svc(ANGLEROTATE *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

POSITION *
getposcontroller_1_svc(void *argp, struct svc_req *rqstp)
{
	static POSITION  result;

	/*
	 * insert server code here
	 */

	return &result;
}

SERVOS *
getservoscontroller_1_svc(void *argp, struct svc_req *rqstp)
{
	static SERVOS  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
checkerror_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
setgripcontroller_1_svc(double *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
checkbarriercontroller_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

COLORRGB *
getcolorcontroller_1_svc(void *argp, struct svc_req *rqstp)
{
	static COLORRGB  result;

	/*
	 * insert server code here
	 */

	return &result;
}

PROXIMITYSENSORS *
getsensorscontroller_1_svc(void *argp, struct svc_req *rqstp)
{
	static PROXIMITYSENSORS  result;

	/*
	 * insert server code here
	 */

	return &result;
}
