/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "controller.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
controller_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		POSITION movecontroller_1_arg;
		POSITION movetocontroller_1_arg;
		ANGLEROTATE rotatecontroller_1_arg;
		double setgripcontroller_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case INITCONTROLLER:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) initcontroller_1_svc;
		break;

	case MOVECONTROLLER:
		_xdr_argument = (xdrproc_t) xdr_POSITION;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) movecontroller_1_svc;
		break;

	case MOVETOCONTROLLER:
		_xdr_argument = (xdrproc_t) xdr_POSITION;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) movetocontroller_1_svc;
		break;

	case ROTATECONTROLLER:
		_xdr_argument = (xdrproc_t) xdr_ANGLEROTATE;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rotatecontroller_1_svc;
		break;

	case GETPOSCONTROLLER:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_POSITION;
		local = (char *(*)(char *, struct svc_req *)) getposcontroller_1_svc;
		break;

	case GETSERVOSCONTROLLER:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_SERVOS;
		local = (char *(*)(char *, struct svc_req *)) getservoscontroller_1_svc;
		break;

	case CHECKERROR:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) checkerror_1_svc;
		break;

	case SETGRIPCONTROLLER:
		_xdr_argument = (xdrproc_t) xdr_double;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) setgripcontroller_1_svc;
		break;

	case CHECKBARRIERCONTROLLER:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) checkbarriercontroller_1_svc;
		break;

	case GETCOLORCONTROLLER:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_COLORRGB;
		local = (char *(*)(char *, struct svc_req *)) getcolorcontroller_1_svc;
		break;

	case GETSENSORSCONTROLLER:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_PROXIMITYSENSORS;
		local = (char *(*)(char *, struct svc_req *)) getsensorscontroller_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (CONTROLLER, CONTROLLERVERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, CONTROLLER, CONTROLLERVERS, controller_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CONTROLLER, CONTROLLERVERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, CONTROLLER, CONTROLLERVERS, controller_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CONTROLLER, CONTROLLERVERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
