/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "controller.h"

bool_t
xdr_POSITION (XDR *xdrs, POSITION *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->n, 3,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->o, 3,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->a, 3,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->p, 3,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_SERVOS (XDR *xdrs, SERVOS *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->num_servos))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->q, 5,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ANGLEROTATE (XDR *xdrs, ANGLEROTATE *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->axis))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->angle))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_GRIP_STATE (XDR *xdrs, GRIP_STATE *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->open))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->barrier))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_COLORRGB (XDR *xdrs, COLORRGB *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->red))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->green))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->blue))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->red);
		IXDR_PUT_LONG(buf, objp->green);
		IXDR_PUT_LONG(buf, objp->blue);
		}
		 if (!xdr_double (xdrs, &objp->tolerance))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->idname))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->code, 7,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->red))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->green))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->blue))
				 return FALSE;

		} else {
		objp->red = IXDR_GET_LONG(buf);
		objp->green = IXDR_GET_LONG(buf);
		objp->blue = IXDR_GET_LONG(buf);
		}
		 if (!xdr_double (xdrs, &objp->tolerance))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->idname))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->code, 7,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->red))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->green))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->blue))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->tolerance))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->idname))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->code, 7,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_PROXIMITYSENSORS (XDR *xdrs, PROXIMITYSENSORS *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->num_left_sensors))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->left_sensors, 10,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->num_right_sensors))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->right_sensors, 10,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->num_top_sensors))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->top_sensors, 10,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->num_back_sensors))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->back_sensors, 10,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}
