/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "controller.h"


void
controller_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	char *initcontroller_1_arg;
	int  *result_2;
	POSITION  movecontroller_1_arg;
	int  *result_3;
	POSITION  movetocontroller_1_arg;
	int  *result_4;
	ANGLEROTATE  rotatecontroller_1_arg;
	POSITION  *result_5;
	char *getposcontroller_1_arg;
	SERVOS  *result_6;
	char *getservoscontroller_1_arg;
	int  *result_7;
	char *checkerror_1_arg;
	int  *result_8;
	double  setgripcontroller_1_arg;
	int  *result_9;
	char *checkbarriercontroller_1_arg;
	COLORRGB  *result_10;
	char *getcolorcontroller_1_arg;
	PROXIMITYSENSORS  *result_11;
	char *getsensorscontroller_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CONTROLLER, CONTROLLERVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = initcontroller_1((void*)&initcontroller_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = movecontroller_1(&movecontroller_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = movetocontroller_1(&movetocontroller_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = rotatecontroller_1(&rotatecontroller_1_arg, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = getposcontroller_1((void*)&getposcontroller_1_arg, clnt);
	if (result_5 == (POSITION *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = getservoscontroller_1((void*)&getservoscontroller_1_arg, clnt);
	if (result_6 == (SERVOS *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_7 = checkerror_1((void*)&checkerror_1_arg, clnt);
	if (result_7 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_8 = setgripcontroller_1(&setgripcontroller_1_arg, clnt);
	if (result_8 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_9 = checkbarriercontroller_1((void*)&checkbarriercontroller_1_arg, clnt);
	if (result_9 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_10 = getcolorcontroller_1((void*)&getcolorcontroller_1_arg, clnt);
	if (result_10 == (COLORRGB *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_11 = getsensorscontroller_1((void*)&getsensorscontroller_1_arg, clnt);
	if (result_11 == (PROXIMITYSENSORS *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	controller_1 (host);
exit (0);
}
